// <auto-generated />
using Ef_Traineemanagement;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Trainee_Management_System.Migrations
{
    [DbContext(typeof(TraineeContext))]
    [Migration("20231208083251_flip")]
    partial class flip
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Ef_Traineemanagement.Trainee", b =>
                {
                    b.Property<int>("Empno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("worklocation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Empno");

                    b.ToTable("Traineedetails");
                });
#pragma warning restore 612, 618
        }
    }
}
